owner: endosulistio
repo: tukarcoid-status

sites:
  - name: Tukarcoid
    url: https://tukar.co.id
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico
  - name: WSS Tukarcoid
    url: https://socket.tukar.co.id:6001/socket.io/socket.io.js
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico
  - name: PUSH Tukarcoid
    url: https://push.tukar.co.id/sms
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tukar.co.id
  # baseUrl: /tukarcoid-status
  logoUrl: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/icon.png
  name: Tukarcoid Status
  introTitle: "About this site"
  introMessage:  Welcome to Tukarcoid real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
