owner: endosulistio
repo: tukarcoid-status

sites:
  - name: Tukarcoid
    url: https://tukar.co.id
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico
  - name: WSS Tukarcoid
    url: https://socket.tukar.co.id:6001/socket.io/socket.io.js
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico
  - name: PUSH Tukarcoid
    url: https://push.tukar.co.id/sms
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/favicon.ico

status-website:
  cname: status.tukar.co.id
  logoUrl: https://raw.githubusercontent.com/endosulistio/tukarcoid-status/master/assets/icon.png
  introTitle: "About this site"
  name: Tukarcoid Status
  introMessage: Welcome to Tukarcoid real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
